global:
  scrape_interval: 15s

scrape_configs:
  - job_name: fiapx-api
    metrics_path: /api/actuator/prometheus
    static_configs:
      - targets: ["api-service:8080"]
  - job_name: fiapx-processor
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["processor-service:8081"]
