{
 "title": "FIAP X — Visão geral",
 "tags": [
  "fiapx",
  "fase5"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requisições HTTP por segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"fiapx-api\"}[1m]))",
     "legendFormat": "API"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"fiapx-processor\"}[1m]))",
     "legendFormat": "Processor"
    }
   ]
  },
  {
   "title": "Latência p95 — API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{job=\"fiapx-api\"}[5m])) by (le))",
     "legendFormat": "API p95"
    }
   ]
  },
  {
   "title": "Disponibilidade dos serviços",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"fiapx-.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}